language: ruby

services:
  - mysql

rvm:
  - 2.3.1

env:
  - REDMINE_VER=3.2.4
  - REDMINE_VER=3.3.1

before_install:
  - export PLUGIN_NAME=redmine_skype_link
  - export DB=mysql
  - export REDMINE_PATH=$HOME/redmine
  - git clone --depth=1 --branch=$REDMINE_VER https://github.com/redmine/redmine.git $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

install:
  - bundle install

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME RUBYOPT="-W0"
